name: cd-dispatch

on:
  repository_dispatch:
    types: [mudblazor-release]
    

jobs:
  update-package:
   name: Update Package
   runs-on: ubuntu-latest
   defaults:
    run:
      working-directory: ./src

   steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup dotnet version
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: ${{ github.event.client_payload.dotnet-version }}
        
    - name: Update MudBlazor
      run: |
          dotnet add ./Try.Core/Try.Core.csproj package MudBlazor --version ${{ github.event.client_payload.mud-version }}
          dotnet add ./TryMudBlazor.Client/TryMudBlazor.Client.csproj package MudBlazor --version ${{ github.event.client_payload.mud-version }}
        
  pipeline:
    name: Pipeline
    uses: MudBlazor/TryMudBlazor/.github/workflows/template-pipeline.yml@master
    with:
      dotnet-version: ${{ github.event.client_payload.dotnet-version }}
      deploy-web-app: true
      deploy-condition: 'refs/heads/main'
      deploy-web-app-name: trymudblazor
      deploy-web-app-slot-name: staging
    secrets:
      publish-profile: ${{ secrets.PUBLISH_TRY_MUDBLAZOR }}
