name: cd-dispatch

on:
  repository_dispatch:
    types: [mudblazor-release]
    

jobs:
  update-package:
   name: Update Package
   runs-on: ubuntu-latest
   defaults:
    run:
      working-directory: ./src

   steps:
    - name: Sleeper
      run: sleep 5m
   
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup dotnet version
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: ${{ github.event.client_payload.dotnet-version }}
        
    - name: Update MudBlazor
      run: |
          dotnet add ./Try.Core/Try.Core.csproj package MudBlazor --version ${{ github.event.client_payload.mud-version }}
          dotnet add ./TryMudBlazor.Client/TryMudBlazor.Client.csproj package MudBlazor --version ${{ github.event.client_payload.mud-version }}
    
    - name: Commit Message
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Updated MudBlazor to ${{ github.event.client_payload.mud-version }}" -a
    
    - name: Commit & Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        
  pipeline:
    name: Pipeline
    needs: update-package
    uses: MudBlazor/TryMudBlazor/.github/workflows/template-pipeline.yml@main
    with:
      dotnet-version: ${{ github.event.client_payload.dotnet-version }}
      deploy-web-app: true
      deploy-condition: 'refs/heads/main'
      deploy-web-app-name: trymudblazor
      deploy-web-app-slot-name: staging
    secrets:
      publish-profile: ${{ secrets.PUBLISH_TRY_MUDBLAZOR }}
