name: ci-cd

on:
  push:
  pull_request:

jobs:
  pipeline:
    name: Pipeline
    uses: MudBlazor/Workflows/.github/workflows/template-pipeline.yml@main
    with:
      dotnet-version: 6.0.x
      deploy-web-app: true
      deploy-condition: 'refs/heads/dev'
      deploy-web-app-name: trymudblazor-dev
    secrets:
      publish-profile: ${{ secrets.PUBLISH_TRY_MUDBLAZOR_DEV }}
