name: ci-dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:
    

jobs:
  pipeline:
    name: Pipeline
    uses: MudBlazor/TryMudBlazor/.github/workflows/template-pipeline.yml@dev
    with:
      dotnet-version: 5.0.x
      deploy-web-app: false
