name: ci-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    

jobs:
  pipeline:
    name: Pipeline
    uses: MudBlazor/TryMudBlazor/.github/workflows/template-pipeline.yml@main
    with:
      dotnet-version: 6.0.x
      deploy-web-app: false
