name: deploy-prod

on:
  workflow_dispatch:
    inputs:
        deploy-task:
          description: 'Publish to staging or swap slots'
          required: true
          default: 'publish' 
          type: choice
          options:
          - publish
          - slot-swap

jobs:
  pipeline:
    if: ${{ github.event.inputs.deploy-task == 'publish' }}
    uses: MudBlazor/Workflows/.github/workflows/template-pipeline.yml@main
    with:
      dotnet-version: 6.0.x
      deploy-web-app: true
      deploy-condition: 'refs/heads/main'
      deploy-web-app-name: trymudblazor
      deploy-web-app-slot-name: staging
      working-directory: ./src/TryMudBlazor.Server
    secrets:
      publish-profile: ${{ secrets.PUBLISH_TRY_MUDBLAZOR }}
      
  azure-slot-swap:
    if: ${{ github.event.inputs.deploy-task == 'slot-swap' }}
    uses: MudBlazor/Workflows/.github/workflows/azure-app-service.yml@main
    with:
      azure-app-name: trymudblazor
    secrets:
      azure-cred: ${{ secrets.AZURE_CREDENTIALS_TRY_PROD }}
