name: manual-deploy

on:
  workflow_dispatch:
    

jobs:
  pipeline:
    name: Pipeline
    uses: MudBlazor/TryMudBlazor/.github/workflows/template-pipeline.yml@main
    with:
      dotnet-version: 6.0.x
      deploy-web-app: true
      deploy-condition: 'refs/heads/main'
      deploy-web-app-name: trymudblazor
      deploy-web-app-slot-name: staging
    secrets:
      publish-profile: ${{ secrets.PUBLISH_TRY_MUDBLAZOR }}
